models/TaskType.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "task_type".
 *
 * @property string $id
 * @property string $name
 * @property string $description
 *
 * @property Task[] $tasks
 */
class TaskType extends \yii\db\ActiveRecord
{

    use ModelOwner;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'task_type';
    }

    public static function fieldName()
    {
        return 'task_type_id';
    }

    /**
     * @param int $taskGroupId Task group id
     * @param string $name Task type name
     * @return TaskType
     */
    public static function findByTaskGroupIdAndName($taskGroupId, $name)
    {
        $rels = TaskTypeToTaskGroup::find()
            ->select('task_type_id')
            ->where(['task_group_id' => $taskGroupId])
            ->all();

        $taskTypeIds = [];
        foreach ($rels as $item) {
            $taskTypeIds[] = $item->task_type_id;
        }

        return TaskType::find()
            ->where(['in', 'id', $taskTypeIds])
            ->andWhere(['name' => $name])
            ->one();
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name'], 'string', 'max' => 64],
            [['description'], 'string', 'max' => 128],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'description' => Yii::t('app', 'Description'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTasks()
    {
        return $this->hasMany(Task::className(), ['task_type_id' => 'id']);
    }

    public static function getListByTasksIds(array $tasksIds)
    {
        return self::getListBySlavesIds('task_type', 'task_type_id', 'task', 'task_id', $tasksIds);
    }
}

controllers/TaskController.php
<?php

namespace app\controllers;

use app\models\Action;
use app\models\ActionHistory;
use app\models\actions\Created;
use app\models\actions\Exception as ActionExcpetion;
use app\models\actions\Modified;
use app\models\actions\ToActual;
use app\models\actions\ToCompleted;
use app\models\actions\ToPostponed;
use app\models\ChatMessage;
use app\models\Order;
use app\models\TaskTypeToTaskGroup;
use Yii;
use app\models\Task;
use app\models\TaskGroup;
use app\models\TaskType;
use app\models\User;
use yii\base\ErrorException;
use yii\helpers\Json;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => [
                    'view', 'create', 'update',
                    'delete', 'get-task-types',
                    'create-double', 'do-action',
                    'set-status',

                ],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'view' => ['get', 'post'],
                    'create' => ['get', 'post'],
                    'update' => ['post'],
                    'delete' => ['post'],
                    'set-status' => ['post'],
                    'do-action' => ['post'],
                    'get-task-types' => ['get'],
                ],
            ],
        ];
    }

    /**
     * Displays a single Task model.
     * @param string $id
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        $user = Yii::$app->getUser();
        if (!$user->can('view_task')
            && !$user->can('view_task', ['model' => $model])
        ) {
            throw new ForbiddenHttpException(Yii::t('app', 'You can not view the task'));
        }

        $viewData = $this->prepareViewData($model);
        return $this->renderAjax('view', $viewData);
    }

    /**
     * Creates a new Task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @param string $actual_to
     * @return mixed
     * @throws ForbiddenHttpException
     * @throws BadRequestHttpException
     */
    public function actionCreate($actual_to = null)
    {
        if (!Yii::$app->getUser()->can('create_task')) {
            throw new ForbiddenHttpException(Yii::t('app', 'You can not create a task'));
        }

        if ($actual_to !== null && !preg_match('/\d{4}\-\d{2}\-\d{2}/', $actual_to)) {
            throw new BadRequestHttpException(Yii::t('app', 'Invalid "{param}" format', ['param' => 'actual_to']));
        }

        $model = new Task();
        $isDataLoaded = $model->load(Yii::$app->request->post());
        $saved = $isDataLoaded && $model->save();
        if (!$saved) {
            $model->actual_to = null;
        }

        if (!$isDataLoaded) {
            $viewData = $this->prepareViewData($model, $saved);
            return $this->renderAjax(
                $saved ? 'view' : 'create',
                array_merge($viewData, ['actual_to' => $actual_to])
            );
        } else {
            return Json::encode(
                [
                    'task_id' => $model->id,
                ]
            );
        }
    }

    /**
     * Updates an existing Task model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws ForbiddenHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if (!Yii::$app->getUser()->can('update_task', ['model' => $model])) {
            throw new ForbiddenHttpException(Yii::t('app', 'You can not update the task'));
        }

        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                $actModified = new Modified([], $model);
                $actModified->run();
                $actModified->historyRecord((string)$model);
            }
        }

        $viewData = $this->prepareViewData($model, true);
        return $this->renderAjax('view', $viewData);
    }

    /**
     * @return string
     * @throws BadRequestHttpException
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     */
    public function actionCreateDouble()
    {
        if (($id = Yii::$app->request->post('task_id', null)) === null) {
            throw new BadRequestHttpException(Yii::t('app', 'Required param "{name}" is missing', ['name' => 'task_id']));
        }

        $model = $this->findModel($id);
        if (!Yii::$app->user->can('create_task_double', ['model' => $model])) {
            throw new ForbiddenHttpException(Yii::t('app', 'You can not create the task double'));
        }

        $double = new Task();
        $double->actual_to = $model->actual_to;
        $double->user_id = Yii::$app->user->id;
        $double->task_type_id = $model->task_type_id;
        $double->task_group_id = $model->task_group_id;
        $double->name = $model->name;
        $double->status = $model->status;
        $double->for_all = $model->for_all;

        $double->save();

        $viewData = $this->prepareViewData($double, true);
        return $this->renderAjax('view', $viewData);
    }

    /**
     * @return string
     * @throws BadRequestHttpException
     * @throws NotFoundHttpException
     * @throws ForbiddenHttpException
     */
    public function actionSetStatus()
    {
        if (($id = Yii::$app->request->post('task_id', null)) === null) {
            throw new BadRequestHttpException(Yii::t('app', 'Required param "{name}" is missing', ['name' => 'task_id']));
        }

        if (($status = Yii::$app->request->post('status', null)) === null) {
            throw new BadRequestHttpException(Yii::t('app', 'Required param "{name}" is missing', ['name' => 'status']));
        }

        $json = Yii::$app->request->post('json', false);

        $task = Task::findOne($id);
        if (!$task) {
            throw new NotFoundHttpException(Yii::t('app', 'Task not found'));
        }

        if (!Yii::$app->getUser()->can('update_task', ['model' => $task])) {
            throw new ForbiddenHttpException(Yii::t('app', 'You can not update the task'));
        }

        if ($task->status == $status) {
            throw new BadRequestHttpException(Yii::t('app', 'Current status is same as new status'));
        }

        $action = null;
        switch ($status) {
            case Task::STATUS_NOT_COMPLETED:
                $action = new ToActual([], $task);
                break;
            case Task::STATUS_COMPLETED:
                $action = new ToCompleted([], $task);
                break;
            case Task::STATUS_POSTPONED:
                $action = new ToPostponed([], $task);
                break;
            default:
                throw new BadRequestHttpException(Yii::t('app', 'Unknown status'));
        }

        $actionError = $actionHistory = null;
        try {
            $action->run();
            $actionHistory = $action->historyRecord();
        } catch (ActionExcpetion $e) {
            $actionError = $e->getMessage();
        }

        return $this->prepareResponseAfterAction($task, $json, $actionError, $action, $actionHistory);
    }

    /**
     * @return string
     * @throws BadRequestHttpException
     * @throws ForbiddenHttpException
     * @throws Exception
     */
    public function actionDoAction()
    {

        $taskId = Yii::$app->request->post('task_id', null);
        if ($taskId === null) {
            throw new BadRequestHttpException(Yii::t('app', 'Required param "{name}" is missing', ['name' => 'task_id']));
        }

        $task = Task::findOne($taskId);
        if ($task === null) {
            throw new BadRequestHttpException(Yii::t('app', 'Unknown task'));
        }

        if (!Yii::$app->user->can('do_action', ['model' => $task])) {
            $viewData = $this->prepareViewData($task);
            return $this->renderAjax(
                'view', array_merge($viewData, ['action_error' => Yii::t('app', 'You do not have permission to do the action')])
            );
        }

        $actionClassName = Yii::$app->request->post('action_class', null);
        if ($actionClassName === null) {
            throw new BadRequestHttpException(Yii::t('app', 'Required param "{name}" is missing', ['name' => 'action_class']));
        }

        $json = Yii::$app->request->post('json', false);

        $actionClass = '\app\models\actions\\' . $actionClassName;
        if (!class_exists($actionClass)) {
            throw new BadRequestHttpException(Yii::t('app', 'Unknown action'));
        }
        $methods = [
            'getIntersectionNames',
            'run',
        ];
        foreach ($methods as $item) {
            if (!method_exists($actionClass, $item)) {
                throw new \app\models\actions\Exception(Yii::t('app', 'Action method "{method}" not found', ['method' => $item]));
            }
        }

        $taskGroupIntersectionNames = TaskTypeToTaskGroup::getIntersectionNamesByTaskGroupAndTaskType(
            $task->task_group_id, $task->task_type_id
        );
        $actionIntersectionNames = call_user_func("$actionClass::getIntersectionNames");
        if (count(array_intersect($taskGroupIntersectionNames, $actionIntersectionNames)) == 0) {
            throw new \app\models\actions\Exception(

views/task/_add_new_action.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use trntv\yii\datetime\DateTimeWidget;

/** @var $action_error string */
/** @var $model \app\models\Task */
/** @var $optional_date string */
?>
    <h4><?= Yii::t('app', 'Add new Action') ?></h4>
<?php if ($action_error && strlen($action_error) > 0): ?>
    <div class="alert alert-danger">
        <?= nl2br($action_error) ?>
    </div>
<?php endif; ?>
<?php
echo Html::beginForm(Url::toRoute('/task/do-action'), 'POST', ['class' => 'form-action-do']);
?>
<?= Html::hiddenInput('task_id', $model->id) ?>
    <div class="form-group">
        <?= Html::label(Yii::t('app', 'Action'), 'action-list') ?>
        <?= Html::dropDownList('action_class', null, $model->getActionClassesAsListItems(), ['class' => 'form-control', 'id' => 'action-list']) ?>
    </div>
    <div class="form-group">
        <?= Html::label(Yii::t('app', 'Note'), 'action-message') ?>
        <?= Html::input('text', 'note', null, ['class' => 'form-control', 'id' => 'action-note']) ?>
    </div>
    <div class="form-group">
        <?= Html::label(Yii::t('app', 'Date'), 'action-date') ?>
        <?php
        echo DateTimeWidget::widget(
            [
                'name' => 'optional_date',
                'options' => [
                    'id' => 'optional-date',
                ],
                'momentDatetimeFormat' => Yii::$app->params['actual_to_date_format_moment'],
                'clientOptions' => [
                    'allowInputToggle' => true
                ]
            ]
        );
        ?>
    </div>
    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Add'), ['class' => 'btn btn-primary']) ?>
    </div>
<?= Html::endForm() ?>

views/task/_manage.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/** @var $show_create_double bool */
?>
<div class="list-group-item">
    <h4 class="list-group-item-heading"><?= Yii::t('app', 'Manage') ?></h4>
    <?php if (isset($show_create_double) && $show_create_double): ?>
    <div class="list-group-item-text">
        <?= Html::beginForm(Url::toRoute('/task/create-double'), 'POST', ['id' => 'form-create-double']) ?>
        <?= Html::hiddenInput('task_id', $model->id) ?>
        <div class="form-group">
            <?= Html::submitButton(Yii::t('app', 'Create a Double'), ['class' => 'btn btn-warning']) ?>
        </div>
        <?= Html::endForm(); ?>
    </div>
    <?php endif; ?>
    <?php if ($model->status != \app\models\Task::STATUS_COMPLETED): ?>
        <div class="list-group-item-text">
            <?= Html::beginForm(Url::toRoute('/task/set-status'), 'POST', ['class' => 'form-set-status']) ?>
            <?= Html::hiddenInput('task_id', $model->id) ?>
            <?= Html::hiddenInput('status', \app\models\Task::STATUS_COMPLETED) ?>
            <div class="form-group">
                <?= Html::submitButton(Yii::t('app', 'To Completed'), ['class' => 'btn btn-success']) ?>
            </div>
            <?= Html::endForm(); ?>
        </div>
    <?php endif; ?>
    <?php if ($model->status != \app\models\Task::STATUS_POSTPONED): ?>
        <div class="list-group-item-text">
            <?= Html::beginForm(Url::toRoute('/task/set-status'), 'POST', ['class' => 'form-set-status']) ?>
            <?= Html::hiddenInput('task_id', $model->id) ?>
            <?= Html::hiddenInput('status', \app\models\Task::STATUS_POSTPONED) ?>
            <div class="form-group">
                <?= Html::submitButton(Yii::t('app', 'To Postponed'), ['class' => 'btn btn-primary']) ?>
            </div>
            <?= Html::endForm(); ?>
        </div>
    <?php endif; ?>
    <?php if ($model->status != \app\models\Task::STATUS_NOT_COMPLETED): ?>
        <div class="list-group-item-text">
            <?= Html::beginForm(Url::toRoute('/task/set-status'), 'POST', ['class' => 'form-set-status']) ?>
            <?= Html::hiddenInput('task_id', $model->id) ?>
            <?= Html::hiddenInput('status', \app\models\Task::STATUS_NOT_COMPLETED) ?>
            <div class="form-group">
                <?= Html::submitButton(Yii::t('app', 'To Actual'), ['class' => 'btn']) ?>
            </div>
            <?= Html::endForm(); ?>
        </div>
    <?php endif; ?>
</div>

views/task/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use trntv\yii\datetime\DateTimeWidget;
use yii\base\Widget;

/* @var $this yii\web\View */
/* @var $model app\models\Task */
/* @var $form yii\widgets\ActiveForm */
/* @var $task_group_list_items array */
/* @var $task_type_list_items array */
/* @var $user_list_items array|null */
/* @var $actual_to string */
/* @var $date_format string */



$can_update = $model->isNewRecord || Yii::$app->user->can('update_task', ['model' => $model]);
?>

<div class="task-form">

    <?php  Widget::$autoIdPrefix = 'task-create-w'; ?>

    <?php
    $form = ActiveForm::begin(
        [
            'id' => 'form-task-create',
            'action' => $model->isNewRecord ? Url::toRoute('/task/create') : Url::toRoute(['/task/update', 'id' => $model->id]),
            'method' => 'POST',
        ]
    );
    ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true, 'disabled' => !$can_update]) ?>

    <?= $form->field($model, 'task_group_id')->listBox($task_group_list_items, ['id' => 'task-groups', 'disabled' => !$can_update, 'size' => 6]) ?>

    <?php $isTaskTypesListDisabled = count($task_type_list_items) == 0 || !$can_update; ?>
    <?= $form->field($model, 'task_type_id')->listBox($task_type_list_items, ['id' => 'task-types', 'disabled' => $isTaskTypesListDisabled, 'size' => 6]) ?>

    <?= $form->field($model, 'for_all')->checkbox(['id' => 'for-all', 'disabled' => !$can_update]) ?>

    <?php
    $options = [
        'id' => 'date-selector',
        'placeholder' => $model->isNewRecord
            ? (new \DateTime())->format(Yii::$app->params['actual_to_date_format_php'])
            : '',
        'disabled' => !$can_update,
    ];
    if (isset($actual_to) && $actual_to != null) {
        $options['value'] = Yii::$app->formatter->asDate($actual_to, 'php:' . $date_format);
    }
    echo $form->field($model, 'actual_to')->widget(
        DateTimeWidget::className(),
        [
            'options' => $options,
            'phpDatetimeFormat' => 'php:' . Yii::$app->params['actual_to_date_format_php'],
            'momentDatetimeFormat' => Yii::$app->params['actual_to_date_format_moment'],
            'clientOptions' => [
                'allowInputToggle' => true
            ]
        ]
    )
    ?>

    <?php if ($user_list_items !== null): ?>
        <?= $form->field($model, 'user_id')->listBox($user_list_items, ['id' => 'user-list', 'disabled' => !$can_update]) ?>
    <?php endif; ?>

    <?php if ($can_update): ?>
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['id' => 'submit', 'class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
    <?php endif; ?>

    <?php ActiveForm::end(); ?>
</div>
<script type="text/javascript">
    (function($) {
        /*
         If submit button is clicked then send form`s data via ajax request and
         prevent native request.
         */
        var submitButton = $("form#form-task-create button[type=submit]");
        var modalWindowBlock = $("div#modal");
        var modalWindowBlockContentBlock = modalWindowBlock.find("div#modal-content");
        $("form#form-task-create").on('beforeSubmit', function(event) {

            var form = $(this);
            submitButton.prop("disabled", true);

            var dataToSend = form.serialize();

            modalWindowBlockContentBlock.html("<div class=\"loader-container\"><img src=\"/img/loader.gif\" alt=\"Loading...\" /></div>");

            $.ajax({
                url: form.attr("action"),
                method: form.attr("method"),
                dataType: "json",
                data: dataToSend,
                success: function(response) {
                    modalWindowBlock.modal("hide");
                },
                error: function(response) {
                    modalWindowBlockContentBlock.html(response.responseText);
                }
            });

            return false;
        });

        /*
         If task groups list value changes then request
         task types assigned to the selected task group.
         */
        var taskTypesListBox = $("select#task-types");
        $("select#task-groups").change(function(event) {

            var theListBox = $(this);
            var groupId = theListBox.val();

            submitButton.prop("disabled", true);
            theListBox.prop("disabled", true);
            taskTypesListBox.prop("disabled", true);

            $.ajax({
                url: "<?= Url::toRoute('/task/get-task-types') ?>",
                method: "GET",
                dataType: "json",
                data: {group_id: groupId},
                success: function(response) {

                    taskTypesListBox.html("");
                    var firstVal = null;
                    for (var i = 0; i < response.length; ++i) {
                        var item = response[i];
                        if (firstVal === null) {
                            firstVal = item.id;
                        }
                        var option = $("<option>").attr("value", item.id).html(item.description);
                        taskTypesListBox.append(option);
                    }
                    taskTypesListBox.val(firstVal);

                    submitButton.prop("disabled", false);
                    theListBox.prop("disabled", false);
                    taskTypesListBox.prop("disabled", false);
                },
                error: function(response) {
                    modalWindowBlockContentBlock.html(response.responseText);
                }
            });
        });
    })(jQuery);

    /*
    Hide users list if checkbox "For All" is checked or show it if no
     */
    (function($) {

        var userList = $("select#user-list");
        var checkbox = $("input#for-all[type=checkbox]");
        <?php if ($model->isNewRecord && count($model->errors) == 0 && Yii::$app->user->can('view_task')): ?>
        checkbox.prop("checked", true);
        <?php endif; ?>
        if (userList.length > 0) {
            if (checkbox.is(":checked")) {
                userList.parent().hide();
            }

            checkbox.change(function(event) {
                debugger;
                var theCheckbox = $(this);
                if (theCheckbox.is(":checked")) {
                    userList.parent().hide("fast");
                    userList.val("@");
                } else {
                    userList.parent().show("fast");
                }
            });
        }

    })(jQuery);

    /*
    If editing task, show submit button only if edit form is changed
     */
    (function($) {

        var submitButton = $("button#submit");
        <?php if (!$model->isNewRecord): ?>
        submitButton.hide();
        <?php endif; ?>

        $("form#form-task-create input, form#form-task-create select").on("change keypress", function(event) {
            submitButton.show("fast");
        });

        $("form#form-task-create input#date-selector").click(function(event) {
            submitButton.show("fast");
        });

    })(jQuery);

    (function($) {
        /*
         Focus on task name field on load
         */
        var i = setInterval(function() {
            var field = $("input#task-name");
            if (field.length == 0) {
                return;
            }
            field.focus();
            clearInterval(i);
        }, 500);
    })(jQuery);
</script>