controllers/ChatController.php
<?php

namespace app\controllers;

use app\models\ChatMessageSearch;
use app\models\Task;
use Faker\Provider\zh_TW\DateTime;
use Yii;
use app\models\ChatMessage;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\Json;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ChatController implements the CRUD actions for ChatMessage model.
 */
class ChatController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'read'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['create', 'read', 'load-previous'],
                        'roles' => ['@'],
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'create' => ['post'],
                    'read' => ['get'],
                    'load-previous' => ['get'],
                ],
            ],
        ];
    }

    /**
     * Creates a new ChatMessage model.
     *
     * @return mixed
     * @throws BadRequestHttpException
     * @throws NotFoundHttpException
     * @throws ForbiddenHttpException
     */
    public function actionCreate()
    {
        $taskId = Yii::$app->request->post('task_id', null);
        if ($taskId !== null) {
            if (($task = Task::findOne($taskId)) === null) {
                throw new NotFoundHttpException(Yii::t('app', 'The task is not found'));
            }
            if (!Yii::$app->user->can('send_message_to_task', ['model' => $task])) {
                throw new ForbiddenHttpException(Yii::t('app', 'You can not send message to the task'));
            }
        } else {
            if (!Yii::$app->user->can('send_message_to_main_chat')) {
                throw new ForbiddenHttpException(Yii::t('app', 'You can not send message to the main chat'));
            }
        }

        $model = new ChatMessage();
        if ($taskId !== null) {
            $model->task_id = $taskId;
        }
        $model->user_id = Yii::$app->request->post('user_id', null);
        $model->message = Yii::$app->request->post('message', null);

        if ($model->save()) {
            return Json::encode(['success' => true]);
        } else {
            return Json::encode(['success' => false, 'errors' => $model->getErrors()]);
        }
    }

    /**
     * @param int $first_message_id
     * @param int $task_id
     * @return string
     * @throws NotFoundHttpException
     * @throws ForbiddenHttpException
     */
    public function actionLoadPrevious($first_message_id, $task_id = null)
    {
        $this->checkReadAccess($task_id);

        if (!ChatMessage::find()->where(['id' => $first_message_id])->exists()) {
            throw new NotFoundHttpException(Yii::t('app', 'The messages is not found'));
        }

        $messages = ChatMessageSearch::searchPrevious(
            $first_message_id, Yii::$app->params['chat_load_last_messages_count'], $task_id
        );

        return Json::encode(
            [
                'messages' => $this->prepareMessages($messages),
                'has_more' => count($messages) >= Yii::$app->params['chat_load_last_messages_count'],
            ]
        );
    }

    /**
     * @param string $from_timestamp
     * @param int $task_id
     * @return string
     * @throws NotFoundHttpException
     * @throws ForbiddenHttpException
     * @throws BadRequestHttpException
     */
    public function actionRead($from_timestamp, $task_id = null)
    {
        $this->checkReadAccess($task_id);

        $dt = \DateTime::createFromFormat('U.u', $from_timestamp);
        if ($dt === false) {
            throw new BadRequestHttpException('Can not parse timestamp');
        }

        $messages = ChatMessageSearch::search($dt->format('Y-m-d H:i:s'), $task_id);

        return Json::encode(
            [
                'timestamp' => (string)microtime(true),
                'messages' => $this->prepareMessages($messages),
            ]
        );
    }

    /**
     * @param int|null $task_id
     * @throws ForbiddenHttpException
     * @throws NotFoundHttpException
     */
    private function checkReadAccess($task_id = null)
    {
        if ($task_id !== null) {
            if (($task = Task::findOne($task_id)) === null) {
                throw new NotFoundHttpException(Yii::t('app', 'The task is not found'));
            }

            if (!Yii::$app->user->can('read_messages_from_task', ['model' => $task])) {
                throw new ForbiddenHttpException(Yii::t('app', 'You can not read messages from the task'));
            }
        } else {
            if (!Yii::$app->user->can('read_messages_from_main_chat')) {
                throw new ForbiddenHttpException(Yii::t('app', 'You can not read messages from the main chat'));
            }
        }
    }

    /**
     * @param array $messages
     * @return array
     */
    protected function prepareMessages(array $messages)
    {
        $preparedMessages = [];
        foreach ($messages as $item) {
            $preparedMessages[] = [
                'id' => $item->id,
                'username' => $item->user->display_name . '(' . $item->user->username . ')',
                'user_id' => $item->user_id,
                'message' => $item->message,
                'created_at' => $item->created_at,
            ];
        }

        return $preparedMessages;
    }

    /**
     * Finds the ChatMessage model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return ChatMessage the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ChatMessage::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\ActionHistory;
use app\models\ActionHistorySearch;
use app\models\ChatMessage;
use app\models\TaskGroup;
use app\models\TaskType;
use app\models\User;
use Faker\Provider\zh_TW\DateTime;
use Yii;
use yii\db\Expression;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\TaskSearch;
use app\models\Task;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index', 'login', 'logout', 'day', 'week', 'completed'],
                'rules' => [
                    [
                        'actions' => ['index', 'logout', 'day', 'week', 'completed'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['login'],
                        'allow' => true,
                        'roles' => ['?'],
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    private function putListsToViewData(array &$viewData, array $tasksIds)
    {
        $actionsHistories = ActionHistory::getListByTasksIds($tasksIds);
        $ahIds = [];
        foreach ($actionsHistories as $group) {
            foreach ($group as $ah) {
                $ahIds[] = $ah->id;
            }
        }

        $viewData['actions_histories'] = $actionsHistories;
        $viewData['task_groups_for_tasks'] = TaskGroup::getListByTasksIds($tasksIds);
        $viewData['task_types_for_tasks'] = TaskType::getListByTasksIds($tasksIds);
        $viewData['users_for_tasks'] = User::getListByTasksIds($tasksIds);
        $viewData['users_for_action_histories'] = User::getListByActionHistoriesIds($ahIds);
    }

    public function actionIndex()
    {
        $createdAt = ChatMessage::getCreatedAtByIndexFromEnd(
            Yii::$app->params['chat_load_last_messages_count']
        );
        $createdAtDt = $createdAt
            ? \DateTime::createFromFormat('Y-m-d H:i:s', $createdAt)
            : new \DateTime();
            

        $tasksData = $this->prepareTasksUsingCallbackAndTaskIds([$this, 'prepareTasksForADay']);
        $viewData = [
            'tasks' => $tasksData['tasks'],
            'task_groups' => TaskGroup::find()->all(),
            'chat_begin_timestamp' => $createdAtDt->format('U.u'),
            'chat_messages_limit' => Yii::$app->params['chat_load_last_messages_count'],
        ];
        $this->putListsToViewData($viewData, $tasksData['ids']);
        return $this->render('index', $viewData);
    }

    public function actionDay()
    {
        $tasksData = $this->prepareTasksUsingCallbackAndTaskIds([$this, 'prepareTasksForADay']);
        $viewData = [
            'tasks' => $tasksData['tasks'],
        ];
        $this->putListsToViewData($viewData, $tasksData['ids']);
        return $this->renderAjax('_day', $viewData);
    }

    /**
     * @param callback $callback
     *
     * @return array
     */
    private function prepareTasksUsingCallbackAndTaskIds($callback, $parameter = null)
    {
        $tasks = call_user_func($callback, $parameter);
        $tasksIds = [];
        foreach ($tasks as $group) {
            foreach ($group as $t) {
                $tasksIds[] = (int)$t->id;
            }
        }

        return [
            'tasks' => $tasks,
            'ids' => $tasksIds
        ];
    }

    public function actionWeek()
    {
        $tasksData = $this->prepareTasksUsingCallbackAndTaskIds([$this, 'prepareTasksForAWeek']);
        $viewData = [
            'tasks' => $tasksData['tasks'],
        ];
        $this->putListsToViewData($viewData, $tasksData['ids']);
        return $this->renderAjax('_week', $viewData);
    }

    public function actionWeekActionsPerformed()
    {
        $tasksData = $this->prepareTasksUsingCallbackAndTaskIds([$this, 'prepareTasksForAWeek'], true);
        $viewData = [
            'tasks' => $tasksData['tasks'],
            'actions_performed' => true
        ];
        $this->putListsToViewData($viewData, $tasksData['ids']);
        return $this->renderAjax('_week', $viewData);
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    protected function prepareTasksForAWeek($actions_performed = false)
    {
        $userId = Yii::$app->user->can('view_task')
            ? null
            : Yii::$app->user->id;

        $request = Yii::$app->request;
        $name = $request->post('name');
        if (is_string($name)) {
            $name = trim($name);
        }
        $date = $request->post('date');
        $taskGroupId = $request->post('task_group_id', null);

        if ($date !== null) {
            $date = $this->convertDate($date);
            if ($date !== null) {

                $dateDt = new \DateTime($date);
                $dateEndDt = clone $dateDt;
                $dateEndDt = $dateEndDt->add(\DateInterval::createFromDateString('1 weeks'));

                $dateEnd = $dateEndDt->format('Y-m-d');

                unset($dateDtClone);
            }
        }
        if ($date === null) {

            $dateDt = new \DateTime();
            $dateEndDt = clone $dateDt;
            $dateEndDt->add(\DateInterval::createFromDateString('1 weeks'));

            $date = $dateDt->format('Y-m-d');
            $dateEnd = $dateEndDt->format('Y-m-d');
        }

        // Prepare query
        if (!$actions_performed) {
            $query = Task::find()
                ->filterWhere(
                    [
                        'or',
                        ['task.user_id' => $userId],
                        ['for_all' => $userId !== null ? 1 : null],
                    ]
                )->andWhere(
                    '(actual_to >= :date AND actual_to < :date_end) OR actual_to IS NULL',
                    [
                        ':date' => $date,
                        ':date_end' => $dateEnd,
                    ]
                )->andWhere(['status' => Task::STATUS_NOT_COMPLETED]);
        } else {
            $query = Task::find()
                ->joinWith('actionHistories')
                ->filterWhere(
                    [
                        'or',
                        ['task.user_id' => $userId],
                        ['task.for_all' => $userId !== null ? 1 : null],
                    ]
                )
                ->andWhere(
                    [
                        'and',
                        ['>=', 'action_history.created_at', $date],
                        ['<', 'action_history.created_at', $dateEnd],
                    ]
                );
        }
        $query->andFilterWhere(['like', 'task.name', $name])
            ->andFilterWhere(['task.task_group_id' => $taskGroupId]);

        $preparedTasks = [];
        $models = $query->all();
        do {
            $currentDayTasks = [];
            $date = $dateDt->format('Y-m-d');

            if (!$actions_performed) {
                foreach ($models as $task) {
                    if ($task->actual_to === null) {
                        $currentDayTasks[] = $task;
                        continue;
                    }
                    $taskDt = \DateTime::createFromFormat(
                        Yii::$app->params['actual_to_date_format_php'], $task->actual_to
                    );
                    if ($taskDt->format('Y-m-d') === $date) {
                        $currentDayTasks[] = $task;
                    }
                }
            } else {

                /*
                 * Not so fast, but works.
                 * TODO: Make optimization, may be refactoring
                 */
                // For each query result item do
                foreach ($models as $task) {
                    // For each action history record do
                    foreach ($task->actionHistories as $ah) {
                        // Compare action history record creation date and current day date
                        $ahDt = new \DateTime($ah->created_at);
                        if ($ahDt->format('Y-m-d') == $date) {
                            $currentDayTasks[] = $task;
                            continue 2;
                        }
                    }
                }

                /*
                 * The closure help us to find last ActionHistory instance
                 * created at specified date
                 */
                $findLatestAhForDate = function (array $list, \DateTime $dt) {
                    $count = count($list);
                    for ($i = $count - 1; $i >= 0; --$i) {
                        $ahDt = new \DateTime($list[$i]->created_at);
                        if ($ahDt->diff($dt)->days == 0) {
                            return $list[$i];
                        }
                    }
                    return false;
                };
                /*

views/site/_chat.php
<?php
use yii\helpers\Url;

/* @var $this \yii\web\View */
/* @var $chat_begin_timestamp string */
/* @var $chat_messages_limit int */
/* @var $task_id int|null */
/* @var $chat_id string */


$uid = Yii::$app->user->id;
$this->registerJs(
    !isset($task_id) ? 'new Chat(' . $uid . ', "div#chat-' . $chat_id . '");'
        : 'new Chat(' . $uid . ', "div#chat-' . $chat_id . '", ' . $task_id . ');',
    \yii\web\View::POS_READY
);
?>
<div id="chat-<?= $chat_id ?>" class="panel panel-info">
    <div class="panel-heading">
        <?= Yii::t('app', 'Chat') ?>
        <?php if (!isset($task_id)): ?>
        <div class="pull-right">
            <i class="glyphicon glyphicon-menu-down cursor-pointer chat-expander"></i>
        </div>
        <?php endif; ?>
    </div>
    <div class="panel-body chat-container"<?php if(!isset($task_id)): ?> style="display: none;"<?php endif; ?>>
        <div data-timestamp="<?= $chat_begin_timestamp ?>"
             data-url="<?= Url::toRoute('/chat/read') ?>"
             data-user-id="<?= Yii::$app->user->id ?>"
             class="well well-sm chat-contents-container">
            <div class="center-block" style="text-align: center;">
                <img alt="<?= Yii::t('app', 'Loading...') ?>" src="/img/loader_mini.gif" style="display: none;" />
                <a class="previous" href="<?= Url::toRoute('/chat/load-previous') ?>">
                    <?= Yii::t('app', 'Load previous messages') ?>
                    <i class="glyphicon glyphicon-menu-up"></i>
                </a>
            </div>
        </div>
        <form class="form-chat" action="<?= Url::toRoute('/chat/create') ?>" method="POST"
              enctype="application/x-www-form-urlencoded">
            <div class="form-group">
                <label for="chat-message" class="control-label"><?= Yii::t('app', 'Message') ?></label>
                <input class="form-control" id="chat-message" name="message" type="text" />
            </div>
            <input type="hidden" name="user_id" value="<?= Yii::$app->user->id ?>" />
                <button type="submit" class="btn btn-primary"><?= Yii::t('app', 'Send') ?></button>
        </form>
    </div>
</div>

views/site/_day.php
<?php

/* @var $tasks array */
/* @var $actions_histories */
/* @var $task_groups_for_tasks */
/* @var $task_types_for_tasks */
/* @var $users_for_tasks */
/* @var $users_for_action_histories */
$this->registerJsFile('@web/js/popovers-day-week.js', ['depends' => \yii\web\JqueryAsset::className()]);
?>
<br />
<?php
$count = 0;
foreach ($tasks as $group => $items) {
    $count += count($items);
}
?>
<?php if ($count == 0): ?>
    <h1><?= Yii::t('app', 'Empty search Result') ?></h1>
    <?php return; ?>
<?php endif; ?>
<?php 
$show_tasks_list = function ($view, $group, $title, $dateAttr) use (
    $tasks, $actions_histories,
    $task_groups_for_tasks, $task_types_for_tasks,
    $users_for_tasks, $users_for_action_histories
) {
    if (!isset($tasks[$group]) && count($tasks[$group]) == 0) {
        return null;
    } 
    return $view->render(
        '_tasks_list', 
        [
            'tasks' => $tasks[$group], 
            'title' => $title, 
            'date_attr' => $dateAttr,
            'actions_histories' => $actions_histories,
            'task_groups_for_tasks' => $task_groups_for_tasks,
            'task_types_for_tasks' => $task_types_for_tasks,
            'users_for_tasks' => $users_for_tasks,
            'users_for_action_histories' => $users_for_action_histories,
        ]
    );
} 
?>
<?php if (isset($tasks['actual']) && count($tasks['actual']) > 0): ?>
    <?= $show_tasks_list($this, 'actual', Yii::t('app', 'Actual Tasks'), 'actual_to') ?>
<?php endif; ?>
<?php if (isset($tasks['not_completed']) && count($tasks['not_completed']) > 0): ?>
    <?= $show_tasks_list($this, 'not_completed', Yii::t('app', 'Not Completed Tasks'), 'actual_to') ?>
<?php endif; ?>
<?php if (isset($tasks['postponed']) && count($tasks['postponed']) > 0): ?>
    <?= $show_tasks_list($this, 'postponed', Yii::t('app', 'Postponed Tasks'), 'actual_to') ?>
<?php endif; ?>
<?php if (isset($tasks['completed']) && count($tasks['completed']) > 0): ?>
    <?= $show_tasks_list($this, 'completed', Yii::t('app', 'Completed Tasks'), 'actual_to') ?>
<?php endif; ?>

views/site/error.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

</div>

views/site/index.php
<?php

use yii\bootstrap\Tabs;
use yii\bootstrap\ButtonGroup;
use yii\bootstrap\Button;
use yii\bootstrap\Modal;
use yii\helpers\Html;
use yii\helpers\Url;
use trntv\yii\datetime\DateTimeWidget;;

/* @var $this yii\web\View */
/* @var $tasks array */
/* @var $task_groups array */
/* @var $chat_begin_timestamp string */
/* @var $chat_messages_limit */
/* @var $actions_histories */
/* @var $task_groups_for_tasks */
/* @var $task_types_for_tasks */
/* @var $users_for_tasks */
/* @var $users_for_action_histories */

$this->title = Yii::t('app', 'Tasks');
$this->registerJsFile('@web/js/ajax-search.js', ['depends' => \yii\web\JqueryAsset::className()]);
$this->registerJsFile('@web/js/ajax-modals.js', ['depends' => \yii\web\JqueryAsset::className()]);
$this->registerJsFile('@web/js/chat.js', ['depends' => \yii\web\JqueryAsset::className()]);
$this->registerJs(
    '$("div#modal").on("hidden.bs.modal", function(event) {
        var theModal = $(this);
        theModal.find("div#modal-content").html("");
        searchExecutor();
    });'
);
$this->registerJs(
    '
    (function($) {
        moment.locale("ru");
    })(jQuery);
    '
);
$this->registerJs(
    '
    toastr.options.newestOnTop = false;
    toastr.options.closeButton = true;
    toastr.options.progressBar = true;
    toastr.options.preventDuplicates = true;
    toastr.options.positionClass = "toast-bottom-right";
    ',
    \yii\web\View::POS_END
);
$this->registerJs(
    '
    function showToastForChatMessage(sender, date, mainChat) {
        if (mainChat === undefined) {
            mainChat = true;
        }
        var message = mainChat ? "' . Yii::t('app', 'A new chat message') . '" : "' . Yii::t('app', 'New message in a task chat') . '";

        var mDt = moment(date, "YYYY-MM-DD HH:mm:ss");
        var sDt = mDt.format("HH:mm");
        var html = "<b>" + message + ", " + sDt
            + "</b><br /><p>' . Yii::t('app', 'Sender') . ': " + sender + "</p>";

        var oldTimeout = toastr.options.timeOut;
        var oldExtendedTimeout = toastr.options.extendedTimeOut;
        toastr.options.timeOut = 0;
        toastr.options.extendedTimeOut = 0;
        toastr.info(html);
        toastr.options.timeOut = oldTimeout;
        toastr.options.extendedTimeOut = oldExtendedTimeout;

        var sndNotification = document.getElementById("sound-notification");
        if (!!(sndNotification.canPlayType) && typeof(sndNotification.play) !== "undefined") {
            sndNotification.play();
        }
    }
    function showToastForAction(date, action_name, task_name) {

        var mDt = moment(date, "YYYY-MM-DD HH:mm:ss");
        var sDt = mDt.format("HH:mm");
        var html = "<b>' . Yii::t('app', 'An action performed') . '</b>: " + action_name
            + ", " + sDt + ", ' . Yii::t('app', 'Task') . ': " + task_name;

        var oldPositionClass = toastr.options.positionClass = "toast-bottom-right";
        toastr.options.positionClass = "toast-bottom-full-width";
        toastr.success(html);
        toastr.options.positionClass = oldPositionClass;
    }
    function showAlert(message) {
        toastr.warning(message);
    }
    ',
    \yii\web\View::POS_BEGIN
);
?>
<audio id="sound-notification" preload="auto">
    <source src="<?= Url::to('@web/sounds/notification.mp3') ?>">
    <source src="<?= Url::to('@web/sounds/notification.ogg') ?>">
</audio>
<div class="row">
    <div class="col-xs-2">
        <?php
        echo DateTimeWidget::widget(
            [
                'name' => 'date',
                'options' => [
                    'id' => 'date-selector',
                    'placeholder' => date(Yii::$app->params['actual_to_date_format_php']),
                ],
                'phpDatetimeFormat' => 'php:' . Yii::$app->params['actual_to_date_format_php'],
                'momentDatetimeFormat' => Yii::$app->params['actual_to_date_format_moment'],
                'clientOptions' => [
                    'allowInputToggle' => true
                ]
            ]
        ); 
        ?>
    </div>
    <div class="col-xs-2">
        <select id="task_groups" name="task_group" class="form-control">
            <option value="@"><?= Yii::t('app', 'All') ?></option>
            <?php foreach ($task_groups as $tg): ?>
                <option value="<?= $tg->id ?>"><?= $tg->description ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <div class="col-xs-6">
        <div class="input-group">
            <?php
            echo Html::input(
                'text', 'name', '',
                [
                    'id' => 'search-input',
                    'class' => 'form-control',
                    'placeholder' => Yii::t('app', 'Search for...')
                ]
            );
            ?>
            <span class="input-group-btn">
                <?php 
                echo Button::widget(
                    [
                        'label' => Yii::t('app', 'Search!'),
                        'options' => [
                            'id' => 'search-button',
                            'class' => 'btn-default'
                        ],
                    ]
                ); 
                ?>
            </span>
        </div>
    </div>
    <div class="col-xs-2">
        <?php
        echo ButtonGroup::widget(
            [
                'buttons' => [
                    [
                        'label' => Yii::t('app', 'Add New'),
                        'options' => [
                            'class' => 'btn-success modal-opener',
                            'data-modal-title' => Yii::t('app', 'Create new task'),
                            'data-modal-url' => Url::toRoute('/task/create'),
                        ],
                    ],
                ],
            ]
        );
        ?>
    </div>
</div>
<div class="row">
    <div class="col-xs-12" style="height:8px;"></div>
</div>
<div class="row">
    <div class="col-xs-12">
        <?php
        echo $this->render(
            '_chat', [
                'chat_begin_timestamp' => $chat_begin_timestamp,
                'chat_messages_limit' => $chat_messages_limit,
                'chat_id' => 'main'
            ]
        )
        ?>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <?php
        echo Tabs::widget(
            [
                'items' => [
                    [
                        'label' => Yii::t('app', 'Day'),
                        'content' => $this->render(
                            '_day', [
                                'tasks' => $tasks,
                                'actions_histories' => $actions_histories,
                                'task_groups_for_tasks' => $task_groups_for_tasks,
                                'task_types_for_tasks' => $task_types_for_tasks,
                                'users_for_tasks' => $users_for_tasks,
                                'users_for_action_histories' => $users_for_action_histories
                            ]
                        ),
                        'headerOptions' => ['class' => 'tab-header', 'data-url' => Url::toRoute('/site/day')],
                        'options' => ['id' => 'tab-content-day'],
                        'active' => true,
                    ],
                    [
                        'label' => Yii::t('app', 'Week'),
                        'headerOptions' => ['class' => 'tab-header', 'data-url' => Url::toRoute('/site/week')],
                        'options' => ['id' => 'tab-content-week'],
                    ],
                    [
                        'label' => Yii::t('app', 'Acts.Performed'),
                        'headerOptions' => ['class' => 'tab-header', 'data-url' => Url::toRoute('/site/week-actions-performed')],
                        'options' => ['id' => 'tab-content-week-actions-performed']
                    ]
                ]
            ]
        );
        ?>
    </div>
</div>
<?php
Modal::begin(
    [
        'id' => 'modal',
        'size' => Modal::SIZE_LARGE,
        'header' => '<span id="modal-header-title">Modal Window</span>',
        'clientOptions' => [
            'backdrop' => true,
        ]
    ]
);
?>
<div id="modal-content"></div>
<?php Modal::end(); ?>

views/site/login.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = Yii::t('app', 'Login');
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-7\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-2 control-label'],
        ],
    ]); ?>

    <?= $form->field($model, 'username') ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model, 'rememberMe', [
        'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
    ])->checkbox() ?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton(Yii::t('app', 'Login'), ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>